### ISSUE TITLE
Version 1.0.11 keeps forgetting rooms

### ISSUE THREAD

**Issue by twocolddogs** [Luligu/matterbridge-shelly#101]
weird issue has cropped up with latest version where all room allocations are forgotten after a couple of days.

**Comment by Luligu** [comment]
Hi,
Can you remember me what controller are you using?
Cause under all tests with Home I had no issues but another user noticed this with Alexa upgrading to matterbridge 1.6.1 from 1.6.0.
Can you notice if the endpoint numbers got changed?
Matter.js updated some code there that can explain this.

**Comment by twocolddogs** [comment]
Using a raspberry pi. 
HomeKit 18.2

It's happened again tonight

Can I send logs?

**Comment by Luligu** [comment]
Sure send it but I don’t understand iit happens randomly or you did something?
The update of today for instance has been carefully tested and even on my production setup had no issues at all. And I have more then 100 devices there.

**Comment by twocolddogs** [comment]
It just seems to happen a day or so afterwards.

I'm away for a few weeks but will send some logs when back

**Comment by Luligu** [comment]
Feel free to post then when you are back.

**Comment by twocolddogs** [comment]
Hi, have updated to current versions today and everything has held stable. Will let you know if anything changes.
