### ISSUE TITLE
White-/black list by device names

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#105]
Hi,

needed to update my config for white listing blu devices. It now works with MAC address! Thanks for that. But whitelisting by name in the gateway did not work anymore?! From users perspective this is might easier (if you also support the names for normal devices as defined in the web interface)

I know that names are not ideal identifiers since they can be same for different devices and in case of blu devices even different for the same device on different gateways but will be easier for users to figure out I guess.

Is it possible to use MAC-only for non BLU-devices now?

Sorry, but currently have not so much time to check myself.

**Comment by Luligu** [comment]
Hi,
thanks again for your ideas.

We are testing this:

## [1.1.1-dev.2] - 2024-12-18

### Added

- [matter]: Add list of device types and cluster servers used in the plugin for the certification.
- [plugin]: Add the possibility to validate shelly wifi devices by name, id and mac (i.e. you can put in the blacklist and whitelist the device name given in the web UI, the shelly id or the shelly mac).
- [plugin]: Add the possibility to validate shelly BLU devices by name and mac (i.e. you can put in the blacklist and whitelist the device name given in the gateway web UI or the shelly BLU mac). If you put a shelly BLU in the white list, you need to put also his BLU gateway on the white list.

### Changed

- [package]: Updated dependencies.

### Fixed

- [configure]: Fixed async loop.


The readme explain in this way:

### blackList

If the blackList is defined the devices included in the list will not be exposed to Matter. 
For shelly wifi devices use the device name (i.e. the name defined in the device web UI), the device id (i.e. shellyplus2pm-5443B23D81F8) or the device mac (i.e. 5443B23D81F8).
For shelly BLU devices use the device name (i.e. the name defined in the device gateway web UI) or the device mac addr (i.e. 7c:c6:b6:65:2d:87).

### whiteList

If the whiteList is defined only the devices included in the list are exposed to Matter. 
For shelly wifi devices use the device name (i.e. the name defined in the device web UI), the device id (i.e. shellyplus2pm-5443B23D81F8) or the device mac (i.e. 5443B23D81F8).
For shelly BLU devices use the device name (i.e. the name defined in the device gateway web UI) or the device mac addr (i.e. 7c:c6:b6:65:2d:87).
If you add a BLU device in the white list, you need to put also its BLU gateway on the list.


If you have time before it will be published, from the frontend install mattebridge-shelly@dev and restart if you want to try.

**Comment by IvoGruber** [comment]
Did some simple manual tests and works for me. Great improvement! Can't wait for the next release to use this. This will make the current configuration much more readable and usable. Already have some new ideas to improve the usability further and will open a new feature request after the next release. Thanks a lot!

**Comment by Luligu** [comment]
Thanks so much.
To be honest I appreciate all your suggestions.
