### ISSUE TITLE
Duplicate Devices Showing in Apple HomeApp for Shelly Relays

### ISSUE THREAD

**Issue by siginur** [Luligu/matterbridge-shelly#107]
About a week or two ago, all my Shelly devices started showing up in the Apple HomeApp as two devices.
For example, my bedroom cover shows as one device with open/close control, but there’s also a second “device” with options for single/double/long press. I don’t have any buttons, so this extra device doesn’t make sense.
This happens with all my Shelly devices that have a relay. I can’t remove the second device from the HomeApp or hide it. If I add the primary device to the Home Screen, both show up.

Docker is running on RaspberryPi
Hub is the Apple HomePod
matterbridge and plugin are updated to the latest version

**Comment by Luligu** [comment]
Hi,
the second tiles with button configuration are just the Inputs from shelly. 
If you don't need/like/want them on the controller disable inputs in the plugin config, restart, wait for the controller to read again all node and they will be gone (set exposeInput and exposeInputEvent to disabled).

**Comment by siginur** [comment]
If I disable exposeInput and exposeInputEvent, will it affect all my Shelly devices? And will I need to reconnect all my devices after doing this?
Can you explain in simple words what these settings mean?
Here are my questions:
- exposeInput has 4 options. What does each one mean?
- What is the difference between exposeInput and exposeInputEvent?
- What is nocacheList? Can you explain with examples?
- Do I need to add all my devices to the deviceIp list? Or should I do this only if I have trouble discovering devices? If I do, should I also enable enableConfigDiscover?
- I also don’t understand the postfix setting. What is it for?

The documentation and configuration are hard to understand. We need to improve the README by adding examples, detailed instructions, and clear explanations. I’d be happy to help with this once I better understand what’s going on.

**Comment by Luligu** [comment]
Good point!

Since the dev is empty I will add better (I hope) description in the readme instead then answering here so will be for everyone if you don’t mind.

Of course any help with guides and readme is welcomed and appreciated!

**Comment by Luligu** [comment]
https://github.com/Luligu/matterbridge-shelly/blob/dev/README.md

Let me know if something is still not clear.

**Comment by Luligu** [comment]
https://github.com/Luligu/matterbridge-shelly/blob/dev/COMPONENTS.md
