### ISSUE TITLE
Shelly Plus 1PM not recognized in Homekit

### ISSUE THREAD

**Issue by ionutm80** [Luligu/matterbridge-shelly#23]
Hi, I have several Shelly relays from all 3 generations running (1L, Plus 1PM, 1 mini gen.3) / around 15 including 2 EM, matterbridge recognizea them all and I see no error in the logs. However yesterday after updating to 1.4.0 one of the 8 Shelly Plus 1PM shows as not supported in Homekit. I rebooted the Pi where I have matterbrige installed, I have restarted all 3 AppleTVs, I closed and re-opened Home on my iPhone and in vain, one of the Shelly Plus 1PM still shows as not supported. I have even restared this Shelly several times by connecting to its web gui, I checked with Shelly app and it's working perfectly. How can I reset the matter compose/bridge to homekit only for this relay?
Funny thing is that in the picture below from Home app, the 2 lights are in fact also Shelly relays, 1 identical with this troubled one, meaning a Shelly Plus 1PM, and the other one a Shelly 1 Mini Gen3.
![IMG_4979](https://github.com/user-attachments/assets/fe2f82c3-649a-4ee0-a985-0ff6756d2c47)

![IMG_4977](https://github.com/user-attachments/assets/fef4d2a4-a754-4355-8f15-9e63e0ba02de)

**Comment by Luligu** [comment]
Hi,
in the 
[HOME]\Matterbridge\matterbridge-shelly directory there are a few files. 
Can you send me them please so I can check.
Also in the frontend page Devices check your device if something looks wrong or different from the other 1PM.
You can put the shelly id of Pompa piscina in the black list and restart matterbridge, then wait till Home connect and remove your device (can be 1/5 minutes). You will loose your automations and room ... so backup them if needed.
After remove it from black list and restart.

**Comment by ionutm80** [comment]
I have checked in the page Devices and nothing seems wrong versus the other Shelly 1PM. Unfortunatelly I left the country and although I can connect remote I do not have a laptop with me to extract the files you have requested, will do this next week when I come back. But can you help me a littel bit where I can blacklist the Shelly ID in order to follow your proposes procedure?Thanks a lot!

**Comment by ionutm80** [comment]
It worked! I blacklisted, restarted matterbridge, it disappeared from Home, then I de-blacklisted, restarted matterbridge and voila it shows back in home. Thanks a lot!
![IMG_4985](https://github.com/user-attachments/assets/d022af09-6022-4b7f-96b1-d9421e80e62f)

**Comment by Luligu** [comment]
Hi,
glad it worked.
These are typically Home app missing packets somewhere...
Nothing wrong with your device or Matterbridge.
