### ISSUE TITLE
Shelly i3 has no components to add.

### ISSUE THREAD

**Issue by kachyy** [Luligu/matterbridge-shelly#27]
First,
many thanks! great and appreciated project 

one of my Shelly's is i3, use to activate broadlink commands to my ceiling fan.

unfortunately i cant manage to add it.

Matterbridge v1.4.1, from HA, i3 is connected to HA with unicast setting.

info - [09:38:49.694] [Gaya Shelly-i3 fans]: Shelly added Gaya Shelly-i3 fans gen 1 device id shellyix3-E8DB84D6FE11 host 192.168.1.47
info - [09:38:49.694] [Gaya Shelly-i3 fans]: - mac: E8DB84D6FE11
info - [09:38:49.694] [Gaya Shelly-i3 fans]: - model: SHIX3-1
info - [09:38:49.694] [Gaya Shelly-i3 fans]: - firmware: v1.14.0-gcb84623
info - [09:38:49.694] [Gaya Shelly-i3 fans]: - components:
info - [09:38:49.694] [Gaya Shelly-i3 fans]: - wifi_ap (WiFi)
info - [09:38:49.695] [Gaya Shelly-i3 fans]: - wifi_sta (WiFi)
info - [09:38:49.695] [Gaya Shelly-i3 fans]: - wifi_sta1 (WiFi)
info - [09:38:49.695] [Gaya Shelly-i3 fans]: - mqtt (MQTT)
info - [09:38:49.695] [Gaya Shelly-i3 fans]: - coiot (CoIoT)
info - [09:38:49.695] [Gaya Shelly-i3 fans]: - sntp (Sntp)
info - [09:38:49.695] [Gaya Shelly-i3 fans]: - cloud (Cloud)
warn - [09:38:49.702] [Matterbridge shelly plugin]: Device gen 1 device shellyix3-E8DB84D6FE11 host 192.168.1.47 has no components to add.
info - [09:39:49.553] [ShellyMdnsDiscover]: Sent mDNS query for shelly devices.
info - [09:40:49.555] [ShellyMdnsDiscover]: Sent mDNS query for shelly devices.
info - [09:41:49.555] [ShellyMdnsDiscover]: Sent mDNS query for shelly devices.

**Comment by Luligu** [comment]
Hi,
thanks for your appreciation.

We don't have this device. 
Can you send me please the files you find in HOME/Matterbridge/matterbridge-shelly: they are all json files.
I can add it if I have that files.

**Comment by kachyy** [comment]
[matterbridge-shelly.zip](https://github.com/user-attachments/files/16539317/matterbridge-shelly.zip)
[matterbridge-shelly.config.json](https://github.com/user-attachments/files/16539321/matterbridge-shelly.config.json)

from Homeassistant addon_configs\

**Comment by Luligu** [comment]
Hi,
thanks but I need Matterbridge\matterbridge-shelly not .matterbridge\matterbridge-shelly

**Comment by kachyy** [comment]
those are the only ones i see in \addon_configs\a1b84aa7_matterbridge\ related to matterbridge-shelly
the zip is the entire matterbridge-shelly folder inside

is there another place?

**Comment by Luligu** [comment]
Hi,
I just want to follow up. 
I didn't forget this.
The next release should solve this.
I added a configuration for Input events...

**Comment by kachyy** [comment]
With the new version the i3 module is added in matterbridge.
in HomeKit it expose as 1 switch with 3 buttons.
applying the actions on each button doesnt work, not getting any visual feedback also.

in other room i have same module with mongoose FW, added to HK as 3 seperate switches instead of buttons.
maybe this is necessary?

**Comment by Luligu** [comment]
Hi,
so it shows up. Good!

The 3 button are correct cause there were 3 Inputs. On HomeKit do you see them like a momentary button with the usual single, double long press actions?

Can you enable the debug in the plugin config and send me a copy paste of the entire log (hope you don't have hundreds device).

**Comment by kachyy** [comment]
just to update, it was an issue with the Home assistant matterbridge addon
once installed on debian lxc all worked perfectly!
many thanks!!!!

**Comment by Luligu** [comment]
Hi,
I'm glad you sorted it out.
That plugin is not working correctly and the author doesn't want to collaborate with me so... almost all issues come from there.
My best.
