### ISSUE TITLE
Shelly devices with 2 outputs are being grouped together

### ISSUE THREAD

**Issue by LuisCRSousa** [Luligu/matterbridge-shelly#33]
Shelly devices with 2 outputs are being grouped together in homekit. No problem, homekit can separate them, but then I can't add them in two different rooms. Homebridge solves this by separating the outputs of the same shelly device as a single homekit device.

**Comment by twocolddogs** [comment]
+1 for this

I've also got a Shelly 2 that seems to have an extra output of 2 switchs and a blind? Can't exclude the blind from HomeKit.

Would be great to be able to also exclude individual switches rather than just the whole Shelly unit.

**Comment by Luligu** [comment]
> +1 for this
> 
> I've also got a Shelly 2 that seems to have an extra output of 2 switchs and a blind? Can't exclude the blind from HomeKit.
> 
> Would be great to be able to also exclude individual switches rather than just the whole Shelly unit.

Hi, can you send me the files in the HOME/Matterbridge/matterbridge-shelly please?
We don't have that exact device, so I need the response files.
Thanks.

**Comment by twocolddogs** [comment]
[matterbridge-shelly.zip](https://github.com/user-attachments/files/16740096/matterbridge-shelly.zip)

**Comment by Luligu** [comment]
I thanks.
Can you tell me please the shelly id of the device you have issue with ?

**Comment by Luligu** [comment]
> Shelly devices with 2 outputs are being grouped together in homekit. No problem, homekit can separate them, but then I can't add them in two different rooms. Homebridge solves this by separating the outputs of the same shelly device as a single homekit device.

Hi,
yes are right, HomeKit doesn't have this feature. 

But unfortunately I cannot solve the issue.

**Comment by twocolddogs** [comment]
> I thanks.
> 
> Can you tell me please the shelly id of the device you have issue with ?
> 
> If it is "shellyswitch25-4855190323C5" then the reason is that are running on a old firmware "shellyswitch25-4855190323C5".
> 
> If you update it, it will act normally. In the log you should have seen the message to update the firmware I guess. 
> 
> Also other device have updates... do it please if you want them to be correctly supported.
> 
> Let me know please.

Ahhh, didn't see that. Will update now

**Comment by Luligu** [comment]
As a general rule, I suggest to update all to the latest stable. 
If you take a moment to read the log at start, the plugin will tell you all device that have updates.
