### ISSUE TITLE
Disable -shelly plugin forgets room assignments and tile separation 

### ISSUE THREAD

**Issue by twocolddogs** [Luligu/matterbridge-shelly#35]
Accidentally disabled the -shelly plugin thinking I needed to to restart it after a config change.

Once reenabled, all devices were allocated back to the bridge room in HomeKit and any separated tiles and renames were also wiped. 

Expected behaviour - room allocations and custom names would stick (presume this is a HomeKit issue?)

**Comment by Luligu** [comment]
Hi,
sorry for that when it happens to me I'm not happy.

Yes you are correct, HomeKit correctly removes everything like rooms, names and automations when a device is removed.

**Comment by twocolddogs** [comment]
Ahh that makes sense. I wonder if it might be useful to have a warning dialog come up before disabling the Shelly plugin that this will happen?

**Comment by Luligu** [comment]
Hi,
yes would be nicer to have it.

**Comment by Luligu** [comment]
## [1.5.2] - 2024-08-30

### Added

- [frontend]: Added a confirmation message for removing and disabling plugins.
- [matterbridge cli]: Added the parameter `-sudo` to force the use of sudo when installing or updating a package (this is useful when the internal logic is not working in your setup).
- [matterbridge cli]: Added the parameter `-nosudo` to force not using sudo when installing or updating a package (this is useful when the internal logic is not working in your setup).

### Changed

- [package]: Update dependencies.
- [spawn]: Modified the install or update function to add more info in the log.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

Done.
