### ISSUE TITLE
Update packages with Ubuntu Jammy running on Orangpi with Nodejs 22.7.0

### ISSUE THREAD

**Issue by PL67** [Luligu/matterbridge-shelly#36]
Cannot get the BLU devices (Motion, DW, HT) working with HomeKit with EnableBleDiscover checked.

Also, cannot "ungroup" Shelly Plus with add-on and DS18B20 temp sensors. Also impossible to add one temp sensor to other room, all then move to this room.

**Comment by Luligu** [comment]
Hi,
sorry but can you be more specific and provide some log and screenshots to understand what you say please?

**Comment by PL67** [comment]
Thank you for reply.

Sorry for not being detailed. I'm new to this and unexperienced.

I discovered you cannot add the BLU devices in 'Components' bij MAC address.
I have a lot of BLU device, so seemed best option. It will then however register as unknown device.
So I added by Scanned devices and that worked.

BLU Door Window sensor works fine.
BLU Motion does not update in HomeKit, No Motion, No Lux, eventhough  it is correctly displayed and updated in Components.
BLU HT does not update Temperature, but Humidity works
BLU Button1 and Button 1 Tough does not save the Button Actions in HomeKit. Cannot Save message in HomeKit.

Do not see any Warnings. Failure. But for example Humidity is reported in log, not temperature.

Thank You,
Patrick
[Debug Log Mini1PM.docx](https://github.com/user-attachments/files/16728076/Debug.Log.Mini1PM.docx)

**Comment by Luligu** [comment]
Hi,
thanks for your reply.
I will prepare a detailed guide on how to add the BLU devices and get back to you.
We have the same ones so all is verified and correctly working in HomeKit too (my controller).
With the guide it will be easy to sort it out.

**Comment by PL67** [comment]
Any progress on the guide?
I installed a complete new system (single board with Ubuntu) and still same problem. BLU Motion and BLU HT not working properly. All devices Up-to-date and in Components of Shelly Gen3 I see properties changing, but not in HomeKit.

Also Update Matterbridge v1.5.0 to v1.5.1 does not work and also shelly plugin update 0.9.2 does not work.
I click on it, log says updating, but nothing happens. Restart does not help.

Thank you.

**Comment by Luligu** [comment]
Hi,
for the BLU can you enable debug in shelly plugin and restart. After a while (maybe be sure to force some update from the BLU) download the matterbridge log and send it to me.
![image](https://github.com/user-attachments/assets/e2631f9c-83b7-409f-b6de-ef6592b9d969)

For the update depends on how you installed the single board, Also there, please enable the debug for matterbridge, and send me the matterbridge log.
![image](https://github.com/user-attachments/assets/0019dc34-fbeb-4c28-8eca-9d28ded81374)

To add the BLU choose a suitable shelly and pair the BLU devices like this:
![image](https://github.com/user-attachments/assets/514d322b-7015-4c42-8e93-b0aae382bf32)

Enable BLU discover in the plugin config.
![image](https://github.com/user-attachments/assets/177f796a-e9a9-422b-9b6f-628b8bc37c34)

Restart and in the log for the BLU you should see:
![image](https://github.com/user-attachments/assets/e34a752d-c099-4c4d-aaea-114c305cd8a0)
![image](https://github.com/user-attachments/assets/5ce4d99d-800e-482c-82d7-276ec3ce7651)

In the Devices section of the frontend you should see something like this:
![image](https://github.com/user-attachments/assets/581c8e45-b126-4db2-a043-b5bdb47214aa)

Hope this will help.

**Comment by Luligu** [comment]
The guide:
https://github.com/Luligu/matterbridge-shelly/blob/dev/BLU.md

**Comment by PL67** [comment]
Hello Liligu,

Thank you for guide, but I already did all this.
In webui Gen3 I see all sensors change, but not in MatterBridge.
So I removed the BTHome component and added to another Shelly 1PM mini Gen3 and now it works for BLU Motion and also for BLU HT. Very happy about that! So if not working try removing, other Gen3 or Pro device, and add BTHome components. Then restart MatterBridge.

I have Ubuntu Jammy running on Orangpi with Nodejs 22.7.0.
I would be happy to send you the Debug logs, but where to find Logs for not updating Matterbridge and Shelly Plugin?

Can I also update Matterbridge and Plugin via Ubuntu?

Thank you.

**Comment by Luligu** [comment]
> I have Ubuntu Jammy running on Orangpi with Nodejs 22.7.0. I would be happy to send you the Debug logs, but where to find Logs for not updating Matterbridge and Shelly Plugin?

![image](https://github.com/user-attachments/assets/a5e72745-3585-4eaa-8605-e59d0f69396f)

Then restart Matterbridge and try to update Matterbridge itself and the plugin.

Then download the Matterbridge log and send it to me please...

![image](https://github.com/user-attachments/assets/fbdef1da-3843-4147-acf1-d3794c60a53e)

As of my knowledge there is a well know bug in npm preventing to update packages in Docker, I don't if this is your case.

Are you using Docker or systemctl?

**Comment by Luligu** [comment]
> Can I also update Matterbridge and Plugin via Ubuntu?

Sure:

from a terminal:
```
docker exec -it matterbridge /bin/bash
```
inside the shell
```
npm -g install matterbridge matterbridge-shelly
exit
```
Then just restart Matterbridge from the gui. Don't pull again the image cause you will loose the manual updates.

**Comment by PL67** [comment]
hello Luligu,

Thank you for explanation.
No I do not use Docker.

Log file attached for update Matterbridge and a bit later Shelly Plugin
I checked debug, but info also in log?!

I will try update from terminal.

Thank you.
[matterbridge.log](https://github.com/user-attachments/files/16800323/matterbridge.log)

**Comment by Luligu** [comment]
Hi,
thanks for the log.
You are right I see nothing more in the log then the update started. 
I will add messages in the log too.

Can you tell me if you have to use sudo on your system to execute npm install -g ...?

**Comment by Luligu** [comment]
Hi,
if you manage to update manually to 1.5.2, there are more lines in the log to understand your issue.
Let me know.
Thanks.
