### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by barry74** [Luligu/matterbridge-shelly#39]
Hi,
I run Homebridge on Docker Container Manager on Synology nas, this works very good.
I would like to install matterbridge-shelly on Docker also.
Is this possible?
Thanks!

**Comment by barry74** [comment]
Never mind, I have installed Matterbridge in docker, and within Matterbridge I have installed plugin Matterbridge-shelly.
Working fine.

Thanks.

**Comment by Luligu** [comment]
Hi,
actually when you use docker all plugins are already installed in the image. So just add the plugin you want.
