### ISSUE TITLE
Shelly Plus i4 not recognized

### ISSUE THREAD

**Issue by ppawiggers** [Luligu/matterbridge-shelly#40]
I run Matterbridge-Shelly, latest version. In the list of devices I see my Shelly Dimmer 2's (gen 1) and Shelly Plus 1's (gen 3). However, I don't see my Shell Plus i4 (gen 2). In the logs, they seem to be discovered but they just don't show up in the devices list:

```
[Matterbridge shelly plugin] Discovered shelly gen 2 device id shellyplusi4-xxx host 192.168.219.156 port 80
[Matterbridge shelly plugin] Shelly device shellyplusi4-xxx host 192.168.219.156 already discovered
```

**Comment by barry74** [comment]
I also have i4 installed. Make sure to enable 'exposeInputs'. I have momentary buttons connected to i4.

<img width="825" alt="Scherm­afbeelding 2024-09-03 om 08 40 21" src="https://github.com/user-attachments/assets/dbd8ff44-d593-4173-833f-30fa4e0b0fbf">

**Comment by Luligu** [comment]
That's correct.
Shelly Plus i4 only has 4 Inputs. It doesn't show up unless you select momentary.
In a future version I will add a configuration on a device base (like with z2m plugin).
