### ISSUE TITLE
Matterbridge lost connection and update frontend not working

### ISSUE THREAD

**Issue by PL67** [Luligu/matterbridge-shelly#50]
After about a week the Matterbridge lost connection to HomeKit.
Restart does not help for all Shellies.

Update via Frontend, still not working (Ubuntu single board installation)
Manual update gives next message, but did work and all devices are back;

sudo npm -g install matterbridge matterbridge-shelly
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

Let me know if I need to change anything.
Might cause the Matterbridge to stop working after about a week?

Thank you

**Comment by Luligu** [comment]
Hi,
Thursday Apple released the new firmware 18.0 for Home Pod and Apple Tv (also iPhone).

See here: https://github.com/Luligu/matterbridge/discussions/135

For the update check if in your setup you need to put the password to run "sudo npm -g install matterbridge".

If this is the case check here: https://github.com/Luligu/matterbridge/blob/dev/README-SERVICE.md#verify-that-with-your-distro-you-can-run-sudo-npm-install--g-matterbridge-without-the-password

The deprecated warning messages have no consequences so just ignore them (all packages mentioned are from devDependencies). 

For further investigation we need a full log so please enable the log on file for both matterbridge and matter log, restart and them to us please.

**Comment by Luligu** [comment]
Btw I checked and I got this:
```
lligu@ubuntu:~$ sudo npm install -g matterbridge

added 173 packages in 7s

40 packages are looking for funding
  run `npm fund` for details
```

**Comment by Luligu** [comment]
Please let us know if removing the resumption records worked for you.

**Comment by Luligu** [comment]
@PL67 any news?

**Comment by PL67** [comment]
Hello Luligu,

Matterbridge Shelly update again gave deprecated warning, and removed 1, changed 570, but I already did update matterbridge-shelly. But I think all ok if the warning is of no concern.
Also Shelly DW2 and Shelly Motion 2 now working perfectly. So it was not a CoIoT or mcast problem from my side, since I did not change anything.
Shelly Plus Smoke not working, even with wake-up and restart Matterbridge.
And Wall Display's give Object warning; warn - [08:51:00.927] [ShellyWsClient]: Received unknown response from shellywalldisplay-0008XXXXX5D1 host 192.168.20.241: [object Object]. Maybe because of connected HT?

Thank you.

**Comment by Luligu** [comment]
Hi,
- no concerns for the warnings since they are related to devDependencies.
- the old gen 1 devices in my setup sometimes need to be restarted... but all is working correctly
- shelly gas and shelly smoke are supported from version 0.10.0 (we received them 2 days ago)
- I don't have shellywalldisplay and I think that also @tammeryousef1006 doesn't have it: I will ask Shelly to provide one. But you can send me the response file from /Matterbridge/matterbridge-shelly/shellywalldisplay-0008XXXXX5D1.json and I can try to do with it...

My Best.

**Comment by Luligu** [comment]
## [0.10.0] - 2024-09-26

### Added

- [shelly]: Added component Gas.
- [shelly]: Added support for shellygas with firmware v1.14.0 and added Jest test.
- [shelly]: Added component Smoke.
- [shelly]: Added support for shellyplussmoke with firmware v1.4.2 and added Jest test.
- [test]: Added Jest test for ShellyWsServer
- [test]: Added Jest test for ShellyWsClient
- [test]: Added Jest test for real gen 1 devices
- [test]: Added Jest test for real gen 2 devices
- [test]: Added Jest test for real gen 3 devices
- [shelly]: Added a cache validation random interval for all not sleeping devices.

### Changed

- [shelly]: All devices are loaded from cache to speed up the loading phase in huge networks.
- [shelly]: Added electricalSensor device type to Switch, Light and Cover components when enabled (will be supported by Home Assistant v. 2024.10).
- [package]: Updated dependencies.

### Fixed

- [covery]: Fixed cover closed for gen 2 devices.
- [mdns]: Fixed gen discovery.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by Luligu** [comment]
## [0.11.0] - 2024-10-01

### Added

- [shelly]: Added component Illuminance.
- [shelly]: Added support for shellywalldisplay with firmware v2.2.1 and added Jest test.

### Changed

- [ShellyMdnsScanner]: Refactor Jest test.
- [package]: Optimized the package for space and speed for rock-s0.
- [package]: Updated dependencies.

### Fixed

- [ShellyMdnsScanner]: Fixed name discovered for shellyplug-s
- [ShellyDevice]: Fixed normalizeId.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by Luligu** [comment]
Hi,
so Gas sensor, Smoke sensor and walldisplay are supported.
Please let us (@tammeryousef1006) know if you have any issues with them.

If you still encounter any issues with the update let me know how you run Matterbridge.
The reason if you don't use docker can simply be that your setup requires you to put the password for npm install -g whatever.

If that is the case check this please:
https://github.com/Luligu/matterbridge/blob/dev/README-SERVICE.md#verify-that-with-your-distro-you-can-run-sudo-npm-install--g-matterbridge-without-the-password

**Comment by tammeryousef1006** [comment]
Gas sensor, Smoke sensor and wall display are all running great and sending updates normally didn't had any issue with them at all .

**Comment by Luligu** [comment]
I guess we can close this... no answer
