### ISSUE TITLE
error to install matterbridge-shelly plugin version 1.0.2

### ISSUE THREAD

**Issue by Raskio83** [Luligu/matterbridge-shelly#62]
Hi Luigi, I tried to install the plugin matterbridge-shelly plugin but I get the following error, what could be causing it?

--- logs ---

Plugins - Installing plugin: matterbridge-shelly
info - [15:44:14.822] [Matterbridge]: Installing plugin matterbridge-shelly...
spawn - [15:44:16.266] [Matterbridge:spawn]: changed 38 packages in 1s
spawn - [15:44:16.266] [Matterbridge:spawn]: 10 packages are looking for funding run `npm fund` for details
spawn - [15:44:16.277] [Matterbridge:spawn]: child process exited with code 0 and signal null
spawn - [15:44:16.277] [Matterbridge:spawn]: child process closed with code 0 and signal null
notice - [15:44:16.278] [Matterbridge]: matterbridge-shelly installed correctly
info - [15:44:16.278] [Matterbridge]: Plugin matterbridge-shelly installed. Full restart required.
info - [15:44:16.283] [PluginManager]: Added plugin matterbridge-shelly
info - [15:44:16.285] [PluginManager]: Loading plugin matterbridge-shelly type
error - [15:44:16.289] [PluginManager]: Failed to load plugin matterbridge-shelly: SyntaxError: The requested module 'matterbridge' does not provide an export named 'onOffLight'

**Comment by Luligu** [comment]
Hi,
thanks for reporting the issue.

I imagine you are running a too old version of matterbridge.

Can you tell me the version matterbridge and matterbridge-shelly plugin?

Can you provide me the full log please?

https://github.com/Luligu/matterbridge?tab=readme-ov-file#how-to-send-the-debug-log-files

**Comment by Raskio83** [comment]
Thank you Luigi for your prompt reply, here is what you asked for:
Matterbridge Home Assistant plugin -> 2.9.0-PSA	
Matterbridge shelly plugin -> 1.0.2
Home Assistant -> 2024.10.2

Attached are the logs you requested for analysis
![Matterbridge](https://github.com/user-attachments/assets/d99cbcd9-548b-46e6-9b7d-fe5f8b2cd0b2)
[matter.log](https://github.com/user-attachments/files/17368389/matter.log)
[matterbridge.log](https://github.com/user-attachments/files/17368390/matterbridge.log)

**Comment by Raskio83** [comment]
sorry
[matterbridge.log](https://github.com/user-attachments/files/17368429/matterbridge.log)

**Comment by Luligu** [comment]
Hi, 
thanks but with that home assistant plugin matter and matterbridge are not working. 

And you need to update matterbridge to the latest... to use all plugins.
