### ISSUE TITLE
Matter Switch does not update when the shelly switch is changed directly

### ISSUE THREAD

**Issue by cayossarian** [Luligu/matterbridge-shelly#71]
Pair the matter bridge with shelly plugin to Apple Home and add a device (in this case Shelly dimmer) to Apple Home.  The subsequently change the power setting, for example, turn off the Shelly dimmer) directly via the Shelly Web interface, the matter switch for that device does not update.   Using the HA add-on the shelly switch appears correctly without Matterbridge.

**Comment by Luligu** [comment]
Gen 1 devices must be configured like in the readme... without you don't get updates...
