### ISSUE TITLE
Commissioning failed with all my devices.

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#76]
Hi @Luligu, 

I tried to recommission with all my shelly devices detected devices dectected in the standard configuration. But this failed with version 1.0.6.  I had this trouble with version 1.0.4 only once.

I worked around for now by just adding to of my color bulbs to the white list in the config. I will try to add more devices one by one and inform you, when it starts to fail. Please keep in mind that this will might take some time. Since I want to focus on other issues first.

**Comment by Luligu** [comment]
Hi,
can you be more specific please?
Maybe add a screenshot and the logs. 
So we can understand and help you.

**Comment by IvoGruber** [comment]
There is nothing interesting to see in the current logs, and alexa is also not very helpfull. What log-level should I try to use to see more?

**Comment by Luligu** [comment]
"But this failed with version 1.0.6"

This means not too much to me.

What failed?
