### ISSUE TITLE
ColorBulbs RGBW should support both modes (white/color) at the same time

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#77]
Hi @Luligu,

as discussed with @tammeryousef1006 I would love to see, that the bulbs (Shelly Bulb RGBW (SHCB-1)) support both modes (color/white) at the same time.

I understand that you use the mode detection for PM2 and 2.5 devices to detect whether they should be exposed as roller shutter or two switches. This is a good idea for those devices, but for the bulbs the user want to switch the bulbs between modes in Alexa by just saying "alexa, XXX warm white" (white mode) , "Alexa, xxx red" (color mode), "Alexa, xxx cold white" ...

The alexa shelly skill supports this and it is useful (at least for me) and a blocker to get rid of the shelly alexa skill (using the cloud) and skip to matterbridge.

I assume this needs some more refactoring on the code base?! But I am willing to help and bei patient. Tell me, if you need more informations.

**Comment by Luligu** [comment]
Sorry IvoGruber, 
but who are you?
Cause it seems to me that you have coding skills but your GitHub account is absolutely empty.

Concerning the SHCB-1, as I wrote you before, it has two running mode. 

When in color mode it doesn't accept color temperature commands unless you change mode.
Same when is in white mode.
If I change mode while running (that is possible on shelly side) then I need to configure the light like a HueSaturation and ColorTemp from the beginning on the Matter side.
I need to consider the mode of this device not a device configuration but only the current status of the light component like the colorMode in Matter or Zigbee.

I will think how to do it.

**Comment by IvoGruber** [comment]
Thanks. would be great if you can find a good solution. I know that this can mean a lot of work, even if it looks somewhat simple from the non coding perspective.

Yes, I am a software developer./architect. I have some private projects (all currently inactive) on Gitlab. I just created the Github account because it was neccessary for HACS.

I already cloned matterbridge and matterbridge-shelly. So if you want me to test something, you just need to tell me which branch I need to test. So you do not need to create releases just for testing. (It just sometimes takes time for me to find time slots between work and family).

Currently I just struggle with matterbrige-shelly. Can not build it, since it seems to need matterbridge-stuff?! Did not find time yet to figure out how to solve this or what I am doing wrong yet.

**Comment by Luligu** [comment]
Hi,
thanks for sharing.

Concerning the SHCB-1, I already finished (Jest test included). Need time for @tammeryousef1006 and I test in real and will be released tomorrow.
Thanks for the suggestion.

For testing the easier is docker but not the latest, use the dev cause there there are also the dev of all plugins when they have one.

For building is super easy: clone the dev or the main of matterbridge-shelly. Then:
npm install -g matterbridge --omit=dev (or if you want to use your cloned matterbridge: from the root of package: npm link).
From the root of shelly package then npm install, npm link matterbridge, npm run build (or use the script npm run deepCleanBuild).

Unlike homebridge, here the plugins are super small and fast to load. On a raspberrypi5 you restart with hundreds of endpoints in 1 sec. This allows also to use a low powered device like Radxa rock-s0 with hundreds of endpoint without issues.

**Comment by Luligu** [comment]
Or if you want the tgz to install it directly join us on Discord group: https://discord.gg/QX58CDe6hd.

There I can send files.

**Comment by Luligu** [comment]
## [1.0.7] - 2024-10-23

### Added

- [shelly]: Added both mode HueAndSaturation and ColorTemp to Shelly Bulb (SHCB-1) with switching between color and white mode.

### Changed

- [package]: Updated dependencies.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by IvoGruber** [comment]
Managed to build the latest head with your instructions. Runs mostly as expected. Just had a small glitch after the first voice command to turn the bulb to red. Guess it was in white mode before. It switched to color mode, turned red and than turned white with approximate 30%(?) brightness. Later voice commands did not show things like that. Great work. Thanks a lot. :+1:

**Comment by Luligu** [comment]
We can also use a discussion if you want...
