### ISSUE TITLE
Get rid of intermediate devices?!

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#78]
Hi @Luligu,

after pairing the Matterbridge with Alexa I get

1. The matterbridge aggregator,
2. a device named as in the settings of the shelly device (as in the webfrontend of the device, not as in the app) that also seems to work like an aggregator(!?) and
3. finally the real device that you want to use and this one gets now names auto-genenrated from alexa like "fifth light".

Is it really necessary to have these intermediate "aggregators" as in 2 (I do not have much knowledge about the matter internals but the AVM Smarthome Gateway acts as a matterbridge and does not need these intermediate devices)? I would like just to have the type 3 devices and the matterbrige-aggregator. Also these type 3 devices should get the names configured in the webfrontend of the shelly device. This makes it much easier for people with many devices to pair and use their devices in alexa.

**Comment by Luligu** [comment]
Ask the Alexa guys about this... I agree with you.

I'm not a real fan of Alexa and for Matter support it's not the best controller.

In Matter there is a root note, an aggregator and as many devices as you want connected to it.
All the rest is created by Alexa....

**Comment by IvoGruber** [comment]
Narf, tried out the Home Assistant controller with matterbridge and everything looks great. I just wonder what [AVM](https://avm.de/) is doing different with it's [FRITZ!Smart Gateway](https://avm.de/produkte/smart-home/fritzsmart-gateway/). It work's fine with Home Assistant and Alexa?!

**Comment by Luligu** [comment]
Yes, 
Home Assistant is the most advanced Matter controller.
They support also almost completely the new Matter 1.2 and 1.3 devices types and clusters.
If you want to take a look install the example dynamic plugin and pair with Home Assistant.
My best.
