### ISSUE TITLE
Shelly 1 (SHSW-1) with addon an temp/humidity sensor does not provide temp/humidity

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#82]
Hi @Luligu,

I have a Shelly 1 (Gen1) device and the matching (old) AddOn attached to it with a temperature/humidity sensor (I think its the DHT22 but this maybe does not matter). The web interface of the device presents both temperature and humidity automatically but the shelly plugin complains repetitive with the following error messages and consequently does not expose the values to matter as expected:

error - [02:39:28.178] [Matterbridge shelly plugin]: Device shelly1-MAC host 192.168.x.x does not have component temperature
error - [02:39:28.180] [Matterbridge shelly plugin]: Device shelly1-MAC host 192.168.x.x does not have component temperature
error - [02:39:28.183] [Matterbridge shelly plugin]: Device shelly1-MAC host 192.168.x.x does not have component humidity
error - [02:39:38.176] [Matterbridge shelly plugin]: Device shelly1-MAC host 192.168.x.x does not have component temperature
error - [02:39:38.178] [Matterbridge shelly plugin]: Device shelly1-MAC host 192.168.x.x does not have component temperature
error - [02:39:38.180] [Matterbridge shelly plugin]: Device shelly1-MAC host 192.168.x.x does not have component humidity

I assume that this will also not work for the Shelly Plus 1 (Gen2) device with the new AddOn?! (I also have this addon if you want me to try it out but do not have it in use currently and also have now free sensor to use it!)

Keep in mind that both AddOns can have different sets of sensors added to the plugin that will provide you with different data. There are at least some on/off (binary) sensors that can be used to trigger automations.

**Comment by Luligu** [comment]
Hi,
thank you for your help about that.

For Shelly 1, I need your help cause I don't have the old AddOn. 
Can you send me the file you find in ./Matterbridge/matterbridge-shelly starting shell1-XXXXXX.json.

For the Shelly Plus Add-on I got it and I will make some test here and get back to you.

My best.

**Comment by IvoGruber** [comment]
Here it is ...
[shelly1-000000000000.json](https://github.com/user-attachments/files/17623867/shelly1-000000000000.json)

**Comment by Luligu** [comment]
Hi,
thanks for your help.

Is really not easy to do without the device, but at least with Jest is working correctly.

I need to ask you to test it with the real device.

## [1.0.9] - 2024-11-06

### Added

- [shelly1]: Added support (beta) for external temperature and humidity addon (thanks IvoGruber).
- [shelly]: Added change of device IP address without restart when mDns detect new IP.
- [CoIoT]: Added cfgChanged event.

### Changed

- [log]: Changed level for CoIoT configuration messages from notice to warn.
- [package]: Requires matterbridge 1.6.0.
- [package]: Updated dependencies.

### Fixed

- [BTHome]: Fixed log level for BLU devices.

[matterbridge-shelly.zip](https://github.com/user-attachments/files/17638676/matterbridge-shelly.zip)

In the zip file there is the tgz. If you have time try it please.

**Comment by IvoGruber** [comment]
Logs looks good already but temperature is toggling quickly between 21.2 C and 21.1 C. this is probably a device issue. Maybe the device is also badly placed?! It's maybe not the job of the plugin, but I would avoid updates with this little changes or make it at least configurable:

info - [03:24:00.003] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tC:21.1
info - [03:24:00.003] [Licht Trempel]: Set endpoint MA-tempsensor:6 attribute TemperatureMeasurement.MeasuredValue from 2120 to 2110
info - [03:24:00.006] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tF:70
info - [03:24:03.776] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tC:21.2
info - [03:24:03.777] [Licht Trempel]: Set endpoint MA-tempsensor:6 attribute TemperatureMeasurement.MeasuredValue from 2110 to 2120
info - [03:24:03.779] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tF:70.2
info - [03:24:08.812] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tC:21.1
info - [03:24:08.812] [Licht Trempel]: Set endpoint MA-tempsensor:6 attribute TemperatureMeasurement.MeasuredValue from 2120 to 2110
info - [03:24:08.814] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tF:70
info - [03:24:13.773] [Licht Trempel]: Shelly message for device shelly1-000000000000 Temperature:temperature:tC:21.2

Could not check yet with Alexa or Home Assistant.

**Comment by IvoGruber** [comment]
Works with Home Assistant.

**Comment by IvoGruber** [comment]
Also works with Alexa.

**Comment by IvoGruber** [comment]
Great Job! Thank you!

**Comment by Luligu** [comment]
Thanks!
I will try to support the addon plus …

**Comment by Luligu** [comment]
Hi,
also the Shelly plus Add.-on is verified... will be published tomorrow.

@tammeryousef1006 tested all addons we have.

Thanks again for your help.


## [1.0.9] - 2024-11-11

### Added

- [shelly1]: Added support (with 1 temperature and 1 humidity) for external temperature and humidity addon (thanks IvoGruber).
- [ShellyPlusAddon]: Verified support with sensor temperature DS18B20.
- [ShellyPlusAddon]: Verified support with sensor temperature and humidity DHT22.
- [shelly]: Added change of device IP address without restart when mDns detect new IP.
- [CoIoT]: Added cfgChanged event.

### Changed

- [log]: Changed level for CoIoT configuration messages from notice to warn.
- [package]: Requires matterbridge 1.6.0.
- [package]: Updated dependencies.

### Fixed

- [BTHome]: Fixed log level for BLU devices.
