### ISSUE TITLE
 [ShellyMdnsScanner]: Warning in mDNS query service:

### ISSUE THREAD

**Issue by pbanane** [Luligu/matterbridge-shelly#84]
Hey,

finally, I made it to install matterbridge and the shelly plugin on my raspberry with a debian on it (Using AHK (ATV 4k) with latest iOS 18.1). In the matterbridge log I got the following error but can't see any option how to configure this:

 
_[ShellyMdnsScanner]: Warning in mDNS query service: The value of "offset" is out of range. It must be >= 0 and <= 374. Received 375_

mDNS finds all shellys and it is working somehow fine (facing also other issues). Not knowing if I can ignore this or it needs some attention. Thanks for your support!

May I ask here if I should create additional issues for the following observations a made?

1.  After raspberry and partially also after matter bridge restart, all connected (and sorted shelly to a room) are back to the Apple Homekit room where the Bridge is located. Also, all automations, namings in AHK are lost / forgotten. 
Same when I reconfigure the shelly device (e.g. changing the name) which requires a matterbridge restart. After this, those devices were again connected to the "bridge room" and everything is gone :(
2. When new devices were added in AHK, I can move them there to another room. It takes a while and different retries until it works.
3.  Some devices showing a Model, Vendor, Serial information, some not. It is not depending on the shelly device itself, 1PM gen2, 1PM gen3 or 2 PM Gen 2 and 3 are affected.
4.  In AHK when I switch the typ e.g. from switch to light, a dialog pops up stating: "Change not possible". After klicking "OK" it anyhow changes the typ of the item.

Thank you very much for your patience and support. 

Best

Tom

nodeVersion | 22.11.0
osType | Linux (6.6.51+rpt-rpi-v8)
osPlatform | linux (arm64)
Matterbridge 1.6.1
Shelly Plugin 1.0.9

**Comment by Luligu** [comment]
Hi,
thank you the logs.

There is something I have never seen before:
[08:39:40.855] [ShellyMdnsScanner] [debug] MdnsScanner discovered shelly gen: 1 device id: shelly-schalter-GARAGENLICHT host: 192.168.177.167 port: 9000 
[08:39:40.862] [ShellyMdnsScanner] [debug] MdnsScanner discovered shelly gen: 1 device id: shelly-GARAGENTOR host: 192.168.177.113 port: 9000 
[08:39:40.866] [ShellyMdnsScanner] [debug] MdnsScanner discovered shelly gen: 1 device id: shelly-vorgarten-DOWNLIGHTS host: 192.168.177.15 port: 9000 
[08:39:40.903] [ShellyMdnsScanner] [debug] MdnsScanner discovered shelly gen: 1 device id: shelly-schalter-keller-LICHT host: 192.168.177.145 port: 9000 

What devices do you have on those IP?
What configuration do you have on the device web page that cause mdns response to port 9000?
Can you please activate all these options:
![image](https://github.com/user-attachments/assets/c30b8b8f-ed47-4f5f-b92c-5513a47bff84)
and also 
![image](https://github.com/user-attachments/assets/2373db3c-1ac7-48a6-a2c3-6b49584f70d5)

then restart completely, wait a few minutes and send me the whole directory Matterbridge/matterbridge-shelly.

@tammeryousef1006 did you ever see Mdns on port 9000?

Thanks.

**Comment by pbanane** [comment]
Quick response regarding the three devices. These are Shelly Gen1 devices with a "homekit firmware" running on it:
https://github.com/mongoose-os-apps/shelly-homekit?tab=readme-ov-file

Attached the config of the plugin. I actived the debug mode as requested and restarting. Waiting a while and uploading then the package. I never changed a port nor configured something like this. Should be all standard.

![Plugin_Config](https://github.com/user-attachments/assets/35f961c7-a25a-4c4a-bc74-2de832740b9a)

**Comment by Luligu** [comment]
Ah ok then is the firmware on those devices that create that mdns response. Load the shelly firmware or put them in the blacklist cause they will never work.

What other issues are still opened for you now?

**Comment by pbanane** [comment]
Still 1, 2 and 4. Devices are new after every restart and all configs / automations in AHK are lost.

**Comment by Luligu** [comment]
They are all the same issue: as I told is related to your setup.
You run matterbridge like service?
Send me the matterbridge.service file. 

You can also check on the devices page of the frontend after each restart if the endpoint numbers change. That is likely the origin of the issue.
How many devices you have ?

**Comment by pbanane** [comment]
Sorry, maybe I read it wrong. I run it as a service as documented in your readme-service.md
I needed to adjust the path.

[Archive.zip](https://github.com/user-attachments/files/17748747/Archive.zip)

You are right, when e.g. I change just the name (for testing purposes to provoke the issue) of the shelly on the shelly WebGUI the matterbridge confirmed that there is a change and I need to restart the bridge:

[13:54:44.642] [PluginManager]: Configured plugin matterbridge-shelly type DynamicPlatform
notice - [13:55:25.601] [Vorgartenlicht]: Shelly device Vorgartenlicht id shelly1pmg3-DCDA0CB16394 host 192.168.177.200 sent config changed rev: 12
notice - [13:55:25.603] [Vorgartenlicht]: If the configuration on shelly device Vorgartenlicht has changed, please restart matterbridge for the change to take effect.

After restarting the bridge (via sudo systemctl restart matterbridge) the Endpoint ID has changed.
Why this also 

I have up to 16 devices, now only 4 in the whitelist.

[Unit]
Description=matterbridge
After=network-online.target

[Service]
Type=simple
Environment=PATH=/home/admin/.nvm/versions/node/v22.11.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
ExecStart=/home/admin/.nvm/versions/node/v22.11.0/bin/matterbridge -service
WorkingDirectory=/home/admin/Matterbridge
Restart=always
RestartSec=10s
StandardOutput=inherit
StandardError=inherit
TimeoutStopSec=30s
User=admin

[Install]
WantedBy=multi-user.target

**Comment by Luligu** [comment]
Hi,
your setup is modified from the standard so you have to check it yourself to understand if there are any errors.

Furthermore using nvm in production is not recommended. Nvm is more for a dev setup.

Concerning the endpoint, every time you change a device serial number (not your case) or the name (that is your case), there will be a new uniqueid on Matter and consequently a new endpoint. In this case the controller will delete the old device and create the new one. Loosing all configuration about the first. 

This explain the issues on the device where you changed the name but not the issues on the other devices if also them are recreated every time.

Check the matterbridge.json after each restart or the devices page in the frontend to understand when in your setup new endpoint are generated.

My best.

**Comment by pbanane** [comment]
Hi,

I installed everything from scratch, without using NVM. No it runs without any issues as far as I can see.
As I am not a Linux expert (more a noob) I used NVM to install node.js as it was part of the original guide here:

https://nodejs.org/en/download/package-manager

Thank you again for spending your time in supporting me!

Maybe as a last question:
What would be the best way how to get npm and node.js on a fresh raspberry linux installation?

**Comment by Luligu** [comment]
Hi,
I’m glad you solved and thank you for pointing out your initial issues.
I will update the readme cause you are right: now nodejs point users to nvm in the main page but is fundamentally not a good choice.

Always install node with nodesource script even because in that way when you sudo apt upgrade, node will be updated too.

My best.
