### ISSUE TITLE
Please do not log passwords

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#86]
Hi @Luligu,

Please comment out line 130 or better remove it in src/platform.ts:
    log.debug(`- password: ${CYAN}${config.password}`);

It's always a bad idea to log passwords, even on debug level. You never know who configures this now or later without knowing that it is exposed to whatever.

See: https://betterstack.com/community/guides/logging/sensitive-data/ (you will maybe find better sources for the why)

Maybe also check your other projects for similar issues.

**Comment by Luligu** [comment]
## [1.0.10] - 2024-11-21

### Added

- [edge]: Preliminary updates to support Matterbridge edge (matter.js new API).
- [Jest]: Refactor Jest real tests for Gen3 devices
- [Jest]: Refactor Jest mock tests for Gen3 devices
- [Jest]: Added Jest mock tests for shellyswitch25 switch and cover mode

### Changed

- [ShellyCommandHandler]: Refactor shellyCommandHandlers.
- [BTHome]: Update scanBTHomeComponents to the new BLU firmware 1.0.20 (model identification changes from v1.0.18).
- [log]: Show username and password with **** in logs.
- [package]: Updated dependencies.

**Comment by IvoGruber** [comment]
Thx!
