### ISSUE TITLE
Support for BluDevices works only for Gateways in the Shelly Cloud

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#88]
Hi @Luligu,,

I tried add a Shelly BLU DoorWindow using a GEN3 device as described. I struggled with the fact, that the Gateway needs to be configured in the Shelly-Cloud. Otherwise it seems not to get updates from the BLU device.

I think you should note that in the documentation.

**Comment by Luligu** [comment]
Hi,
I cannot reproduce this issue.

I imagine that the issue is related to a single device. In my experience some BLU gateways are less effective then others.

All my gateway receive updates even if not connected to cloud. It makes sense to me cause all is local.

**Comment by Luligu** [comment]
### Discord

Tamer (https://github.com/tammeryousef1006) has created the Matterbridge Discord group: https://discord.gg/QX58CDe6hd.

Feel free to join (the link is now permanent)!

**Comment by IvoGruber** [comment]
I can confirm that everything works without shelly cloud via matterbridge now. The strange thing is, that the shelly app itself does not update the blu device states as long as the gateway-device is not in the shelly cloud.

**Comment by IvoGruber** [comment]
Even the process of adding a blu device without having a gateway in the shelly cloud worked now for me. So I can not reproduce that anymore. I think you can close this issue. Thanks for taking time.
