### ISSUE TITLE
Shelly Blu DoorWindow devices will not be found even with Gen3-Gateways

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#89]
Hi @Luligu,

I can not add my Shelly Blu Door/Window devices as described in your documentation. I could fix that in my dev-environment by adding

    if (model.startsWith('SBDW')) return modelsMap['SBDW-002C'];

at line 330 in shellyDevices.ts.

It seems that model string for my device returns "SBDW-2Cxxxx", where xxxx is the end of the mac address of the device.

Whenever I have more time I will check, if this also holds for my blu button, motion and ht devices if you want. In this case they will need similar changes.

**Comment by IvoGruber** [comment]
I can already confirm, that the same problem holds with both of my Blu Buttons (both versions, normal and though, think softwarewise there is no difference). Adding following line fixes the issue:

   if (model.startsWith('SBBT')) return modelsMap['SBBT-002C'];

**Comment by IvoGruber** [comment]
I do not know if you ever could test this, maybe this came with the latest firmware release 1.0.20. I am very sure that this also holds for the BLU HT and Motion sensors now. Just could not test yet, since pairing fails currently. Maybe the devices are to far away from the gateway.

**Comment by IvoGruber** [comment]
Here are the error logs I currently get in production with version 1.0.9 with the matterbridge-shelly plugin that lead me to the fix:
error - [02:47:14.273] [Matterbridge shelly plugin]: Shelly device shelly1minig3-MAC host GATEWAY-IP has an unknown BLU device model Unknown Shelly BLU model SBDW-2Cxxxx
error - [02:47:14.274] [Matterbridge shelly plugin]: Shelly device shelly1minig3-MAC host GATEWAY-IP has an unknown BLU device model Unknown Shelly BLU model SBBT-2Cyyyy

**Comment by Luligu** [comment]
Hi,
you are right:

![image](https://github.com/user-attachments/assets/6d150bf4-d4ae-4a6d-876a-973550f97cab)

This new device model identification only creates problems from FW v1.0.18 and only for new paired devices.

My devices are all up to date and didn't show any issues. 

I had to repair them to see it.

Many thanks as always.

My best.

P.S. Do you have BLU motion too? Cause mine says that latest firmware 1.0.16 so old model identification... but I added the new identification even if is not possible to test now.

**Comment by Luligu** [comment]
## [1.0.10] - 2024-11-21

### Added

- [edge]: Preliminary updates to support Matterbridge edge (matter.js new API).
- [Jest]: Refactor Jest real tests for Gen3 devices
- [Jest]: Refactor Jest mock tests for Gen3 devices
- [Jest]: Added Jest mock tests for shellyswitch25 switch and cover mode

### Changed

- [ShellyCommandHandler]: Refactor shellyCommandHandlers.
- [BTHome]: Update scanBTHomeComponents to the new BLU firmware 1.0.20 (model identification changes from v1.0.18).
- [log]: Show username and password with **** in logs.
- [package]: Updated dependencies.

**Comment by IvoGruber** [comment]
Thx for fixing things that quick! Great job. Devices are working now in production with version 1.0.10!
