### ISSUE TITLE
Devices got reorganized after update of matterbridge from version 1.6.1 to 1.6.2

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#92]
Hi,

I updated matterbridge via "docker compose pull" from version 1.6.1 to 1.6.2. Afterwards almost all devices seem to be rediscovered in Alexa. So the configuration in Alexa (basically the renaming of the devices) got useless again and I will have to rename and configure them again. :-(

Seems that this happened for almost all devices but some devices still remained as before and some devices occur twice now. Do not see any pattern here. At least it has nothing to do with the devices types. Maybe the devices that kept their old names are just dirty left overs?!

The endpoint numbers of the device seem to be much higher than before, but I can not proof it anymore. Maybe that's the reason why Alexa created these new devices and removed the old ones.

I am not sure but I would say previous updates via matterbridge itself did not show theses problems. Will try out that way the next time.

**Comment by Luligu** [comment]
Hi,
I can just imagine that changing the names in Alexa can cause the issue. Like finding new devices when you update.
The device (nodeLabel in Matter) is writable by the controller and persists on restart of the node.
If Alexa writes it then you restart and it doesn’t find the old one and create a new device?

**Comment by IvoGruber** [comment]
So finally all devices was gone and recreated in Alexa with the typical useless names. Updating now from 1.6.2 to 1.6.4 via update mechanism of matterbridge itself did not cause these issues again yet.

**Comment by IvoGruber** [comment]
Using "docker compose pull" again did not cause that problem yet.

**Comment by Luligu** [comment]
I checked the code and I had a possible reason.

I those releases I updated some revisions on the Matter deviceTypes.

It is possible that it causes Alexa to believe they are new...

**Comment by IvoGruber** [comment]
Does not sound so good if that's the reason. Is there any chance to prevent that happening in the future again?! Can imagine that preventing this would be hard to implement by design?! Did this possibly also affect other matter controllers or is this just another thing thats Alexa specific? If just Alexa specific we should add this information to the discussion.

**Comment by Luligu** [comment]
Is difficult to answer. I can only tell that @tammeryousef1006 and I before releasing an update, we test not only new setups from 0 but also the existing setups.
I have Apple in my production setup and never had this issue. Never lost configurations at controller side.
I hope this is not a consequence of renaming the devices in Alexa.
I also didn’t read about this kind of issues since a lot.

**Comment by tammeryousef1006** [comment]
same here , never lost a device over homeassistant , smartthings , google home or alexa  over upgrade

**Comment by IvoGruber** [comment]
Unfortunately I must say the problem is reproducable.

These are the steps to reproduce.

1. Checkout matterbridge with tag 1.6.1 and rebuild in folder "matterbridge"
2. npm install
3. npm run build
4. Checkout matterbridge-shelly with tag 1.0.10 and rebuild in folder "matterbridge-shelly"
5. npm link matterbridge (if needed)
6. matterbridge remove . (if needed to remove matterbridge-shelly)
7. npm install
9. npm run builld
10. matterbridge add . (to add matterbridge-shelly)
11. npm start
12. Ensure that a shellycolorbulb (or any other device) is in the whitelist and noCachelist
13. Restart matterbridge
14. Remove the device from noCachelist
15. Restart matterbridge
16. Check enpoint ID of device in matterbridge
17. Pair with alexa if needed
18. Rename the Hub device in alexa (append " Bridge")
19. Rename the light device in alexa (some other name)
20. Stop matterbridge
21. checkout matterbridge to tag 1.6.2
22. npm install
23. npm build
24. npm start

Now the device gets another endpoint id compared to the one in step 16. Alexa now creates a new Hub device again with name as in the webapp of the device and a new light device with the typical naming scheme (e.g. "First light")

**Comment by IvoGruber** [comment]
To check if this also happens if the devices are not renamed in Alexa, you should use outlet or switch device. Instead of renaming you can than change the type of the outlet device (not the hub) in alexa to light. I would expect that this type is than also gone after updating to 1.6.2. Also the devices should disappear from routines in alexa. If you want I can test this, but will do that later, when got time again.

**Comment by Luligu** [comment]
You don't need to build locally even because the local environment is not verified. (All packages are build inside a workflow with the ideal environment and ubuntu latest with node 20).
Just npm install -g matterbridge@1.6.1 --omit=dev 
Same for mattebridge-shelly.

I will do the test myself.

**Comment by Luligu** [comment]
Hi,
yesterday I finally understood what went wrong in that update.
It is a side effect of removing a cluster from the aggregator to be 100% Matter compliant.
That changed how matter.js store the endpoint numbers.
Thanks for pointing it up.

**Comment by IvoGruber** [comment]
Thx for investigating! BTW: got new endpoint ids with the last update again, but this time did not need to reconfigure things in Alexa. :+1:
