### ISSUE TITLE
[FEATURE-REQUEST] Whitelist/Blacklist BLU-Devices

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge-shelly#93]
Hi,

I would like to whitelist or blacklist BLU devices in the plugin configuration. Maybe I am doing it wrong but it seems to be not supported.

I know I can add/remove them from the gateway devices but maybe someone has still reasons to keep the configuration there as it is.

**Comment by Luligu** [comment]
The idea is that you can exclude all BLU devices with the config.
Then if you add them is cause you want to see them.
But I understand that in real it would be better to validate also BLUs against white and black list (it was already on the TODO list).
Will do it.

**Comment by Luligu** [comment]
I need your feedback on this:

The whitelist doesn't really work for BLUs cause if you put for example only a BLU in the whitelist, it will never be added since the BLUs require their gateway to be added too.

The blacklist is working correctly.

What do you think ?

Add a check against both whitelist and blacklist or only against the blacklist?

**Comment by IvoGruber** [comment]
Imagine you have a lot of BLU devices and you have a reason to add them all to the gateway devices independently from matterbridge. But you only want a few of them to be exposed as matter devices. Than it is easier for the user to whitelist just the few instead of blacklist almost all.

It also can be confusing, if one can only blacklist but not whitelist the devices. If you start on fresh ground people might first want to whitelist to try single devices.

Currently I anyway see only rare use cases. Personally I do not need that feature (even not the blacklist of BLU devices). So I would not give it a very high priority for now unless someone else asks for this feature. But it might blocks "power users" to use matterbridge and those are the ones that can add more feedback and progress to the project.

**Comment by Luligu** [comment]
Ok then I will add the normal white black list and put a note in the readme that whitelisting a BLU works only when also his gateway is white listed.

**Comment by IvoGruber** [comment]
Is this in 1.0.11? Do not find any info in Changelog/Readme and still seems not to work?

**Comment by Luligu** [comment]
## [1.1.0] - 2024-12-09

### Added

- [shelly]: Add shellyIdentifyCommandHandler
- [shelly]: Refactor shellySwitchCommandHandler
- [shelly]: Refactor shellyLightCommandHandler
- [BLU]: Add validate against white and black list for BLU devices. If you put a shelly BLU in the white list, you need to put also his BLU gateway on the white list.
- [BLU]: Add global and single device component black list. You can now exclude a shelly component globally or on a device base.

### Changed

- [colorControl]: Refactor configuration of the cluster.
- [package]: Updated dependencies.

**Comment by Luligu** [comment]
You need the dev cause we are testing it

**Comment by IvoGruber** [comment]
Works for me, but it was somewhat confusing that you have to black/whitelist the name you give it in the gateway. Expected something with MAC address here. Maybe that should be described better in the README or config. Wonder what happens if you name this devices different in two gateways?! Would you need to blacklist/whitelist then both names? If we work with names here, it is maybe also good to work with "names" for the NON-BLU-devices?! Maybe its best to allow always both (name and mac). The MAC combined with some type of the shelly was also confusing in the beginning for me. Most users won't manage to use this feature, since they have additionally to find out, whats the device name to use here.

@Luligu seems to me as this is worth another discussion first. Drop me a note, if I better should start a discussion.

**Comment by Luligu** [comment]
Hi,
that is once again a great idea. Thanks!
I refactored the validation code to support an array instead of a string:
We can validate how the user prefers: Device name or shelly id or blu mac. I will pass both to the validate function.
I will suggest in the readme to always use shelly id and mac for blu cause is unique for each device.
