### ISSUE TITLE
Ghosts in the Home app?

### ISSUE THREAD

**Issue by nurmaso-hub** [Luligu/matterbridge-shelly#94]
When I start matterbridge from the console it runs and everything works. But just for some minutes, then it goes offline and is not accessible on its IP. I run the matterbridge on a raspberry pi parallel to the homebridge and installed matterbridge from the console in homebridge. May that caused an error?

**Comment by nurmaso-hub** [comment]
Bridge is always Matterbridge, like the original device. Interesting point, it depends on the device type.
Always ghosts for: 2.5, mini G3, RGBWs
no ghosts for: i4, Bulbs and plug plus

in the screenshot you see the ghosts for 2 of 3 devices, and the details for the mini G3.

![IMG_3720](https://github.com/user-attachments/assets/13b70c7f-6c40-47dd-9b15-8e2e43f7c8ca)
![IMG_3721](https://github.com/user-attachments/assets/b74e6f9c-ce70-46cf-8427-00f3a7b75f3e)

**Comment by Luligu** [comment]
Sorry for the late reply.

Why you say that they are ghosts?

To understand what is exposed on Matter, go to Devices page of the frontend and check if there are any differences between there and what you see on the Home app.

Sometimes Home takes a while (few minutes) to update the node. The time is clearly related to your network conditions.

**Comment by nurmaso-hub** [comment]
In the frontend there appear 20 devices like its my actually setup. In Homekit in summary appear about 35 devices, like I said some kinds of device are shown up 2 times. And this is since a week and didn’t change. 
For example a RGBW2 is shown as a lamp, and a copy shown up as switch. When I enter the settings of the devices in both of them is shown Matterbridge as the bridge, and in Matterbridge settings are the 20 devices what is right. Even when I go there from the wrong device.

**Comment by Luligu** [comment]
This is not a Matterbridge or Matter issue.
The node has what you see in the frontend.
Home must have some issues due to all the tests you made maybe.
To solve this:
restart matterbridge, wait the controller is connected, then disable the plugins (all). 
wait till you see all devices disappear. Eventually repowoer your controller.
When all devices are gone, enable the plugin.

**Comment by horaciopaulo** [comment]
I had that problem with iOS previous beta and it's solved in the  current one as of December 12 2024. No more ghosts.

**Comment by Luligu** [comment]
Ok, then start from the beginning:
- what controller and version you have ?
- wired or wifi ?

Did you try also to unpair matterbridge (I know is painful), delete all pairing from settings on your phone, repower the controller, factoryreset matterbridge and pair it again?

Is clearly a Home issues. I don't see these kind of problems after version 17.5 of tvOs.

**Comment by Luligu** [comment]
> I had that problem with iOS previous beta and it's solved in the current one as of December 12 2024. No more ghosts.

Exactly the same with version before 17.5

**Comment by nurmaso-hub** [comment]
I use an Apple TV, connected wired with tvOS 18.1
On the iphone iOS 18.2 
I think when its an OS issue, it would be the tvOS and not the phone.

**Comment by Luligu** [comment]
Any news ?

**Comment by nurmaso-hub** [comment]
No, but after I reseted the device storage one day i can add actions to the buttons of the i4’s in homekit, what earlier caused an error.
so everything works, but the issue of doubled devices remains. 
I think I have to arrange with this.

**Comment by Luligu** [comment]
Send me a full backup of your setup to understand where is the problem if it is still there.

**Comment by nurmaso-hub** [comment]
Sure. Problem is still there. I would give you all informations you need. But I’m a bit confused. What do you mean wirh backup of my setup?

**Comment by Luligu** [comment]
<img width="221" alt="image" src="https://github.com/user-attachments/assets/a9a5e742-278d-4bc0-952d-54ed28369b44" />

Can you also send me a screenshot from Home app / Home settings / Home Hubs & Bridges / Bridges (chose matterbridge) / Accessories... 

If you have 20 devices there can show much more if have the inputs enabled in the config... 
They are not ghosts but simply the Inputs components from the shellies.

**Comment by nurmaso-hub** [comment]
Sure, i‘ll do that after the holidays, but i‘ll need 2 weeks.
Until then, i have f.e. an extra button (with 2 inputs) for one RGBW in homekit. You said that is wanted behavior? This button shouldn’t show up. if I want to execute actions on the RGBW i‘ll choose this. i don’t need the buttons in HomeKit. different for i4 or other buttons, these ones should be programmable in homekit.

**Comment by Luligu** [comment]
All components can be blacklisted on a device base if you like.
Check the readme.
Other users may want to have them also for the history on the controller side and not only for automations. New devices allow you to detach the inputs so you can use them for something else.

**Comment by nurmaso-hub** [comment]
To clarify that: F.e. I have only one RGBW in matterbridge, but an actor and a button in homekit. If I would blacklist this one in matterbridge, both would disappear in homekit. also if I hide the button in homekit, the actor would also be hidden. I can’t seperate them. 
After the holidays i‘ll give you the backup, maybe that‘ll help

**Comment by Luligu** [comment]
https://github.com/Luligu/matterbridge-shelly/blob/dev/COMPONENTS.md

**Comment by nurmaso-hub** [comment]
Oh, I didn’t knew this feature. This should work. How about the 2.5s and others?

**Comment by Luligu** [comment]
Is a general function.
It applies to all devices.
Just check the log to learn the component names and ids.
The component id is also shown on the Devices page of the frontend cause it is the child endpoint name.
Feel free to ask if you need help.
@tammeryousef1006 and I will clarify if something is still not clear.

**Comment by nurmaso-hub** [comment]
Hey there, I‘m struggling with that because I don‘t understand where to enter the line with the blacklisted components. In the plugin settings there is just the entry ‚blacklist‘ for complete devices. So where do I enter that?

**Comment by tammeryousef1006** [comment]
here is an example to blacklist a feature for all devices and example of blacklist a function of selected device at shelly plugin

![Screenshot 2025-01-05 184144](https://github.com/user-attachments/assets/f53997d7-4b00-422d-9733-e1cb237ddbb0)

**Comment by nurmaso-hub** [comment]
thx, now I got it. let’s say the documentary is a bit confusing…
solved.

**Comment by Luligu** [comment]
What do you find not clear in the docs? I would like to improve it.

**Comment by nurmaso-hub** [comment]
Now that I got it right, I understand the doc. Don’t know why I got it wrong. Just maybe in the components doc you could add the information from the screenshot (first the device name, then in the right field the component type. and not just the program code line.
and another idea: wouldn’t it make sense to be able to blacklist all components for one device type? f.e. I want to blacklist all Inputs of all rgbw2s. Now I have to enter all my rgbw devices. blacklist all inputs wouldn’t work for me, because for my i4s I need the inputs.

**Comment by tammeryousef1006** [comment]
I got i4s also and i disabled input options at top of config and then added i4s to momentary line , will upload screenshot once im home soon

**Comment by tammeryousef1006** [comment]
the mb can be super customized

![Screenshot 2025-01-06 001644](https://github.com/user-attachments/assets/931bced3-1321-4831-b05c-2969e79af6b2)
![Screenshot 2025-01-06 001625](https://github.com/user-attachments/assets/8d4dd964-a83e-4ea8-b22f-7f8adb599ead)

**Comment by Luligu** [comment]
This the best strategy if you generally don't need Inputs, but you need it only on a few devices.
