### ISSUE TITLE
shellydw2 and shellyflood devices no status updates

### ISSUE THREAD

**Issue by pasqualito79** [Luligu/matterbridge-shelly#98]
Hi there,
I have some shelly 2PM gen 3, 1pm plus and 1 shelllys working great with this plugin, thanks for that!
But with the shellydw2 and shellyflood ones I have issues. I activated them correctly and I also see them in the list of devices. But the status is always "closed". There are no log entries without debug when - for example - I open the door. The status update works immediately with the Shelly app and also with the homebridge plugin from alexryd. I want to get rid of homebridge so I hope we can find the issue....how can I help you find the cause? Thanks in advance...

here are the log entries in debug mode:

I open the door:

 [20:57:54.571] [Türe]: Shelly message for device shellydw2-4026D1 Sensor:sensor:contact_open:true
info - [20:57:54.572] [Türe]: Set endpoint MA-contactsensor:167 attribute BooleanState.StateValue from true to false
info - [20:57:54.573] [Türe]: Shelly message for device shellydw2-4026D1 Lux:lux:value:131
info - [20:57:54.574] [Türe]: Set endpoint MA-lightsensor:165 attribute IlluminanceMeasurement.MeasuredValue from 20828 to 21173
info - [20:57:54.575] [Türe]: Shelly message for device shellydw2-4026D1 Temperature:temperature:value:18.8
info - [20:57:54.575] [Türe]: Set endpoint MA-tempsensor:164 attribute TemperatureMeasurement.MeasuredValue from 1920 to 1880

closing again:
 [20:58:39.631] [Türe]: Shelly message for device shellydw2-4026D1 Sensor:sensor:contact_open:false
info - [20:58:39.632] [Türe]: Set endpoint MA-contactsensor:167 attribute BooleanState.StateValue from false to true
info - [20:58:39.633] [Türe]: Shelly message for device shellydw2-4026D1 Lux:lux:value:121
info - [20:58:39.633] [Türe]: Set endpoint MA-lightsensor:165 attribute IlluminanceMeasurement.MeasuredValue from 21173 to 20828
info - [20:58:39.634] [Türe]: Shelly message for device shellydw2-4026D1 Temperature:temperature:value:18.9
info - [20:58:39.634] [Türe]: Set endpoint MA-tempsensor:164 attribute TemperatureMeasurement.MeasuredValue from 1880 to 1889.9999999999998

nothing happens in Apple Home app, state is always closed.

**Comment by Luligu** [comment]
Hi,
the log is correct... Matter node is updated correctly.

Maybe the controller got disconnected or still has to connect and subscribe.

Check in log when active subscriptions are opened.

Like here:
![image](https://github.com/user-attachments/assets/6f0085ed-e549-4012-829e-ff9ca4d632bb)

**Comment by pasqualito79** [comment]
this is what I get:

info - [21:55:42.481] [SessionManager]: restoring resumption record for node 4067053613840934950 and peer node 4067053613840934950 for fabric index 2
info - [21:55:42.481] [SessionManager]: restoring resumption record for node 2814411069 and peer node 2814411069 for fabric index 1
info - [21:55:42.482] [SessionManager]: restoring resumption record for node 3117698078 and peer node 3117698078 for fabric index 1
info - [21:55:42.482] [SessionManager]: restoring resumption record for node 2415832492 and peer node 2415832492 for fabric index 1
info - [21:55:42.482] [SessionManager]: restoring resumption record for node 1051541755 and peer node 1051541755 for fabric index 1
notice - [21:55:42.493] [Matterbridge]: Matter server started
info - [21:55:42.493] [Matterbridge]: The commissioning server on port 5540 for Matterbridge is already commissioned. Waiting for controllers to connect ...
info - [21:55:42.493] [Matterbridge]: Commissioned fabric information:
info - [21:55:42.494] [Matterbridge]: - fabric index 1 id 4016729412 vendor 4937 (AppleHome) Mein Haus
info - [21:55:42.494] [Matterbridge]: - fabric index 2 id 1892870680 vendor 4996 (AppleKeyChain)
info - [21:56:12.496] [PluginManager]: Configuring plugin matterbridge-shelly type DynamicPlatform
info - [21:56:12.497] [Matterbridge shelly plugin]: Configuring platform matterbridge-shelly
....

**Comment by Luligu** [comment]
There 3 phase you can check:
1) the device send update to the plugin (you see message from the device in the log)
2) the plugin update the node (you see setAttribute in the log)
3) the controller is connected (you see the subscription in the log)

If still you dont see update on the Home app is just a network or controller issue. You can try to restart your controller or maybe disable the plugin, wait that the Home App delete all the devices. Then restart, enable again and check.

**Comment by nuvorussia** [comment]
With your permission i will ask the question here, so as not to create a new topic. Matterbridge is installed on Synology NAS via docker. Shellyflood connected without problems, but in HomeKit it is adopted as a contact sensor (window, door or garage door). So HK does not send notifications as "urgent". Is there a way to fix this problem so that shellyflood is recognized as a leak sensor? Thanks in advance

**Comment by pasqualito79** [comment]
@nuvorussia : That's an easy one - leak sensors are supported with matter 1.3. Apple is only supporting matter 1.2 so you just have to wait and hope it'll arrive soon with an OS update....

**Comment by nuvorussia** [comment]
@pasqualito79 Thank you so much for your help 🤝🏻

**Comment by Luligu** [comment]
Exactly unfortunately Matter supports now almost all kind of devices and clusters, Matterbridge has all of them (check the dynamic examples plugins) but if i use them you won’t see the device at all.
Only controller supporting all is home assistant

**Comment by pasqualito79** [comment]
@Luligu : what about this question I had? "shellyflood is just shown in the upper region as a contact sensor in Apple home. That's ok. But the shellydw2 is also showing two "big" tiles. One with 3 configurable buttons and one with the 3 sensors. From my point of view, this doesn't make sense for this device?"

I can't hide those two tiles in Apple home and in Matterbridge all 3 expose settings are disabled.

**Comment by Luligu** [comment]
So,
shellyflood has 2 endpoint contact sensor and temperature (on Home app you see both in the upper part);

shellydw2 has a lot of endpoint contact sensor, temperature, illuminance and vibration (shows button).

I understand your point of view: with Home app you cannot hide endpoints... with IvoGruber we thought about doing some fine tuning of what is exposed on a device base https://github.com/Luligu/matterbridge-shelly/discussions/97 on the same stile that I use with zigbee plugin.

Will be in the dev tomorrow if I don't get in some issue doing it...

**Comment by Luligu** [comment]
Now you selectively exclude what you don't need.

## [1.1.0] - 2024-12-14

### Added

- [package]: Verified to work with matterbridge edge (matter.js new API).
- [package]: Requires matterbridge 1.6.6.
- [shelly]: Remove from discovered devices the device with mongoose firmware. We ignore them.
- [shelly]: Add shellyIdentifyCommandHandler.
- [BLU]: Add validate against white and black list for BLU devices. If you put a shelly BLU in the white list, you need to put also his BLU gateway on the white list.
- [BLU]: Add global and single device component black list. You can now exclude a shelly component globally or on a device base (available also for BLU devices).
- [matter]: Add tagList to the descriptor cluster.

### Changed

- [shelly]: Refactor shellySwitchCommandHandler.
- [shelly]: Refactor shellyLightCommandHandler.
- [shelly]: Refactor shellyCoverCommandHandler.
- [colorControl]: Refactor configuration of the cluster.
- [electricalSensor]: Refactor electrical measurements initial configuration.
- [matter]: Update all device types.
- [package]: Updated dependencies.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by pasqualito79** [comment]
Thanks! But I don't have a clue how to get the values for the field "component id's" from the shellydw2 device. 
At the moment this is the situation: 
1. I see temperature, illuminance of the room and contact sensor state in the upper fields on Apple home which is fine.
2. I see two big tiles which I want to remove, 1 with some configurable buttons and the second with the contance sensore state but with text "3 sensors".

What I did is enter the shellydw2-device in deviceEntityBlackList property, but what to enter as component name / component id?
